/**
 * Fenrir Ledger — Core TypeScript Types
 *
 * All shared interfaces and type definitions for the data model.
 * See ADR-002 for the household-scoped schema decision.
 */

/** Bonus type for sign-up rewards */
export type BonusType = "points" | "miles" | "cashback";

/**
 * Card status — derived from dates but stored for display performance.
 * See card-utils.ts computeCardStatus() for derivation logic.
 */
export type CardStatus = "active" | "fee_approaching" | "promo_expiring" | "closed";

/**
 * Sign-up bonus details for a credit card.
 * All money amounts are stored as integer cents (USD).
 * All dates are ISO 8601 strings (YYYY-MM-DD).
 */
export interface SignUpBonus {
  /** Reward type: points, miles, or cashback */
  type: BonusType;
  /** Reward amount: points count, miles count, or cashback in cents */
  amount: number;
  /** Minimum spend required to earn the bonus, in cents */
  spendRequirement: number;
  /** Deadline to meet the spend requirement (YYYY-MM-DD) */
  deadline: string;
  /** Whether the spend requirement has been met */
  met: boolean;
}

/**
 * A credit card in the household portfolio.
 *
 * All money amounts are stored as integer cents (USD) to avoid floating-point
 * arithmetic errors. Display layer is responsible for dividing by 100.
 *
 * All dates are stored as ISO 8601 strings:
 * - Date-only fields: YYYY-MM-DD (openDate, annualFeeDate, bonus deadlines)
 * - Timestamp fields: full ISO 8601 (createdAt, updatedAt)
 */
export interface Card {
  /** UUID generated by crypto.randomUUID() */
  id: string;
  /** Foreign key → Household.id */
  householdId: string;
  /** Issuer identifier, e.g. "chase", "amex", "citi", "capital_one" */
  issuerId: string;
  /** Human-readable card name, e.g. "Sapphire Preferred" */
  cardName: string;
  /** Date the card account was opened (YYYY-MM-DD) */
  openDate: string;
  /** Credit limit in cents */
  creditLimit: number;
  /** Annual fee amount in cents (0 if no annual fee) */
  annualFee: number;
  /** Next annual fee due date (YYYY-MM-DD). Empty string if no annual fee. */
  annualFeeDate: string;
  /** Promotional period length in months (0 if no promo period) */
  promoPeriodMonths: number;
  /** Sign-up bonus details, or null if no sign-up bonus */
  signUpBonus: SignUpBonus | null;
  /** Computed status for display. Recalculated on save. */
  status: CardStatus;
  /** Free-form notes */
  notes: string;
  /** ISO 8601 timestamp when this record was created */
  createdAt: string;
  /** ISO 8601 timestamp when this record was last modified */
  updatedAt: string;
}

/**
 * Household — the root entity for Fenrir Ledger's data model.
 *
 * Sprint 1 uses a single hardcoded household ("default-household").
 * Future sprints will support OIDC authentication and multiple households.
 * See ADR-002 for the household-scoped data model decision.
 */
export interface Household {
  /** UUID — "default-household" in Sprint 1 */
  id: string;
  /** Human-readable household name */
  name: string;
  /** ISO 8601 timestamp when this household was created */
  createdAt: string;
}

/** Known card issuers for the issuer dropdown */
export interface Issuer {
  id: string;
  name: string;
}
