/**
 * CSP Inline Script Hashes — Auto-generated by scripts/compute-csp-hashes.mjs
 *
 * Re-generate: node scripts/compute-csp-hashes.mjs
 * Auto-runs:   npm run build  (via prebuild hook)
 * Auto-runs:   npm run dev    (via predev hook)
 *
 * DO NOT EDIT MANUALLY.
 */

/** SHA-256 hash of the next-themes ThemeProvider inline theme-detection script. */
export const NEXT_THEMES_SCRIPT_HASH = "'sha256-LsGgiCZCKM8uXrouB+WIAZ4GmtpIMWe0EJxuJD0PEwQ='";

/**
 * SHA-256 hash of the GA4 inline init script.
 * null when NEXT_PUBLIC_GA4_MEASUREMENT_ID is not set (script will not render).
 */
export const GA4_INIT_SCRIPT_HASH: string | null = null;

/** All inline script hashes to include in script-src CSP directive. */
export const INLINE_SCRIPT_HASHES: string[] = [
  NEXT_THEMES_SCRIPT_HASH,
  ...(GA4_INIT_SCRIPT_HASH ? [GA4_INIT_SCRIPT_HASH] : []),
];
