{{- if ge (int .Values.app.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: odin-throne-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "odin-throne.labels" (dict "component" "monitor") | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: odin-throne
      app.kubernetes.io/component: monitor
---
{{- end }}
{{- if ge (int .Values.ui.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: odin-throne-ui-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "odin-throne.labels" (dict "component" "monitor-ui") | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: odin-throne
      app.kubernetes.io/component: monitor-ui
{{- end }}
