{{- if .Values.secrets.enabled }}
# Template only — actual secrets are created by the CD pipeline via kubectl.
apiVersion: v1
kind: Secret
metadata:
  name: odin-throne-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "odin-throne.labels" (dict "component" "secrets") | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "PLACEHOLDER"
{{- end }}
