apiVersion: v1
kind: Service
metadata:
  name: odin-throne-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "odin-throne.labels" (dict "component" "odins-throne-ui") | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default":"odin-throne-ui-backend-config"}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: odin-throne
    app.kubernetes.io/component: odins-throne-ui
  ports:
    - name: http
      port: 80
      {{- if .Values.oauth2Proxy.enabled }}
      targetPort: oauth2-proxy
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
