apiVersion: v1
kind: Service
metadata:
  name: odin-throne
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "odin-throne.labels" (dict "component" "odins-throne") | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "odin-throne.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: odins-throne
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
